package tr.com.teb.tebws.optimus.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2020-03-30T10:32:02.922+03:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "TEB.WebServiceCard", name = "WebServiceCardHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WebServiceCardHttpPost {

    @WebMethod(operationName = "GetOptimusODM")
    @WebResult(name = "string", targetNamespace = "TEB.WebServiceCard", partName = "Body")
    public String getOptimusODM();

    @WebMethod(operationName = "QueryUpdate")
    @WebResult(name = "string", targetNamespace = "TEB.WebServiceCard", partName = "Body")
    public String queryUpdate(
            @WebParam(partName = "p_ConStr", name = "p_ConStr", targetNamespace = "TEB.WebServiceCard")
                    String pConStr,
            @WebParam(partName = "p_SQL", name = "p_SQL", targetNamespace = "TEB.WebServiceCard")
                    String pSQL,
            @WebParam(partName = "p_FileXml", name = "p_FileXml", targetNamespace = "TEB.WebServiceCard")
                    String pFileXml
    );

    @WebMethod(operationName = "GetOptimusPRD")
    @WebResult(name = "string", targetNamespace = "TEB.WebServiceCard", partName = "Body")
    public String getOptimusPRD();

    @WebMethod(operationName = "WebServiceVersion")
    @WebResult(name = "string", targetNamespace = "TEB.WebServiceCard", partName = "Body")
    public String webServiceVersion();

    @WebMethod(operationName = "GetOptimusPREPROD")
    @WebResult(name = "string", targetNamespace = "TEB.WebServiceCard", partName = "Body")
    public String getOptimusPREPROD();

    @WebMethod(operationName = "GetOptimusDEV")
    @WebResult(name = "string", targetNamespace = "TEB.WebServiceCard", partName = "Body")
    public String getOptimusDEV();

    @WebMethod(operationName = "GetOptimusTST")
    @WebResult(name = "string", targetNamespace = "TEB.WebServiceCard", partName = "Body")
    public String getOptimusTST();
}
